### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-logging#13]
- check existing API functionality
- add missing important API functionality
- check API function signatures and parameters
- enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- plug API functions to existing docs

**Comment by mihaibivol** [comment]
We have an issue regarding this:

* for `Sentry6` the latest working `raven` version is `5.1.0`
* for `raven==5.1.0` I get thiss error when enabling the Celery worker:
```
register_logger_signal(sentry.client, loglevel=level)
TypeError: register_logger_signal() got an unexpected keyword argument 'loglevel'`
```

**Comment by jacquerie** [comment]
...and the hosted Sentry at CERN is version 6.4.4, so we currently can't use `invenio_logging` at CERN!

**Comment by lnielsen** [comment]
Sentry works for me on Zenodo:
- https://github.com/zenodo/zenodo/blob/master/zenodo/config.py#L275
- https://github.com/zenodo/zenodo/blob/master/setup.py#L141

**Comment by mihaibivol** [comment]
@lnielsen the problem is when enabling Sentry in workers `LOGGING_SENTRY_CELERY = True`

**Comment by lnielsen** [comment]
@mihaibivol Ah, got it. I see following solutions:

1) Upgrade sentry.cern.ch to latest Sentry + Raven.
2) Fix [this](https://github.com/inveniosoftware/invenio-logging/blob/master/invenio_logging/sentry.py#L124) call  to something like:

```python
try:
    register_logger_signal(sentry.client, loglevel=level)
except TypeError:
   register_logger_signal(sentry.client)
```

or check which raven distribution is installed.

3) or ``LOGGING_SENTRY_CELERY=False`` until there's a Sentry 7 instance to log to :-)

Will you submit a PR? if not, could I get you to open this as a separate issue instead please.
