### ISSUE TITLE
docs: update structure

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-logging#14]
- introduce new documentation structure https://github.com/inveniosoftware/cookiecutter-invenio-module/issues/56
- document user perspective
- document signals (if not done)
- document example app (if not done)

**Comment by lnielsen** [comment]
Grab documentation of the old documentation on https://github.com/inveniosoftware/invenio/blob/maint-2.1/invenio/ext/logging/__init__.py#L20-L155
