### ISSUE TITLE
error due to old version of raven

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-logging#46]
When I install `invenio-logging[sentry]` it install raven version 4.4 which cause error with `invenio-login`:
```
  File "/Users/maj/devel/virtualenvs/rero-ils-Y_O9MQix/lib/python3.6/site-packages/raven/contrib/flask.py", line 157, in get_user_info
    is_authenticated = current_user.is_authenticated())
```

The constraint should be changed in the `setup.py` file.

**Comment by lnielsen** [comment]
which version are you on? I don't see how it should install raven version 4.4 https://github.com/inveniosoftware/invenio-logging/blob/maint-1.0/setup.py#L37

**Comment by lnielsen** [comment]
I've not been able to reproduce. Please reopen if the problem still persists.
