### ISSUE TITLE
Support for Celery in Sentry

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-logging#6]
Currently special treatment is needed in order to have complete frames analysis in https://github.com/getsentry/raven-python/issues/427, and a tentative partial implementation has been done for INSPIRE OPS branches in: https://github.com/inspirehep/invenio-ext/pull/7 

However INSPIRE implementation does not fully solve the duplicate logging into Sentry.

**Comment by lnielsen** [comment]
@kaplun This has been fully fixed on INSPIRE now right?

**Comment by kaplun** [comment]
I am no longer up-to-date with this. @jacquerie ?

**Comment by lnielsen** [comment]
@jacquerie I'm closing the ticket. Please re-open in case it is still a problem.

**Comment by jacquerie** [comment]
I don't know what to say: this is talking about code I've never touched and problems I never encountered...
